name: tocaan
description: A beautiful weather app built with Flutter, GetX, and Dio.

publish_to: 'none' # for private projects

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # State Management
  get: ^4.6.5
  flutter_svg :
  intl:
  # HTTP Client
  dio: ^5.4.0
  flutter_animate:
  flutter_spinkit: ^5.2.1
  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Fonts
  google_fonts: ^6.1.0

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/effects/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
